import { Book } from "./book";

export const BOOKS_MOCK: Book[] = [
  {
    id: '1',
    title: 'Clean Code',
    authorship: 'Robert C. Martin',
    category: 'Tecnologia',
    isbn: '9780132350884',
    available: true,
  },
  {
    id: '2',
    title: 'The Pragmatic Programmer',
    authorship: 'Andrew Hunt',
    category: 'Tecnologia',
    isbn: '9780201616224',
    available: false,
  },
  {
    id: '3',
    title: 'Domain-Driven Design',
    authorship: 'Eric Evans',
    category: 'Tecnologia',
    isbn: '9780321125217',
    available: true,
  },
  {
    id: '4',
    title: 'Refactoring',
    authorship: 'Martin Fowler',
    category: 'Tecnologia',
    isbn: '9780201485677',
    available: true,
  },
  {
    id: '5',
    title: 'Design Patterns',
    authorship: 'Erich Gamma',
    category: 'Tecnologia',
    isbn: '9780201633610',
    available: true,
  },
  {
    id: '6',
    title: 'Eloquent JavaScript',
    authorship: 'Marijn Haverbeke',
    category: 'Programação',
    isbn: '9781593279509',
    available: true,
  },
  {
    id: '7',
    title: "You Don't Know JS",
    authorship: 'Kyle Simpson',
    category: 'Programação',
    isbn: '9781491904244',
    available: true,
  },
  {
    id: '8',
    title: 'Estruturas de dados e algoritmos em JavaScript',
    authorship: 'Loiane Groner',
    category: 'Programação',
    isbn: '9788575225530',
    available: true,
  },
  {
    id: '9',
    title: 'Algorithms',
    authorship: 'Robert Sedgewick',
    category: 'Ciência da Computação',
    isbn: '9780321573513',
    available: true,
  },
  {
    id: '10',
    title: 'Introduction to the Theory of Computation',
    authorship: 'Michael Sipser',
    category: 'Ciência da Computação',
    isbn: '9781133187790',
    available: true,
  },
  {
    id: '11',
    title: 'Sapiens',
    authorship: 'Yuval Noah Harari',
    category: 'História',
    isbn: '9780062316097',
    available: false,
  },
  {
    id: '12',
    title: 'Guns, Germs, and Steel',
    authorship: 'Jared Diamond',
    category: 'História',
    isbn: '9780393317558',
    available: true,
  },
  {
    id: '13',
    title: 'SPQR',
    authorship: 'Mary Beard',
    category: 'História',
    isbn: '9781631492228',
    available: true,
  },
  {
    id: '14',
    title: 'Brave New World',
    authorship: 'Aldous Huxley',
    category: 'Ficção',
    isbn: '9780060850524',
    available: true,
  },
  {
    id: '15',
    title: 'Fahrenheit 451',
    authorship: 'Ray Bradbury',
    category: 'Ficção',
    isbn: '9781451673319',
    available: true,
  },
  {
    id: '16',
    title: 'A Mão Esquerda da Escuridão',
    authorship: 'Ursula K. Le Guin',
    category: 'Ficção',
    isbn: '9788535914845',
    available: true,
  },
  {
    id: '17',
    title: 'Hello World',
    authorship: 'Hannah Fry',
    category: 'Ciência da Computação',
    isbn: '9780393635003',
    available: true,
  },
  {
    id: '18',
    title: 'Thinking, Fast and Slow',
    authorship: 'Daniel Kahneman',
    category: 'Psicologia',
    isbn: '9780374533557',
    available: false,
  },
  {
    id: '19',
    title: 'Mindset',
    authorship: 'Carol S. Dweck',
    category: 'Psicologia',
    isbn: '9780345472328',
    available: true,
  },
  {
    id: '20',
    title: 'Atomic Habits',
    authorship: 'James Clear',
    category: 'Desenvolvimento Pessoal',
    isbn: '9780735211292',
    available: true,
  },
  {
    id: '21',
    title: 'Deep Work',
    authorship: 'Cal Newport',
    category: 'Desenvolvimento Pessoal',
    isbn: '9781455586691',
    available: true,
  },
  {
    id: '22',
    title: 'The Lean Startup',
    authorship: 'Eric Ries',
    category: 'Negócios',
    isbn: '9780307887894',
    available: true,
  },
  {
    id: '23',
    title: 'The Manager\'s Path',
    authorship: 'Camille Fournier',
    category: 'Gestão',
    isbn: '9781491973899',
    available: true,
  },
  {
    id: '24',
    title: 'Clean Architecture',
    authorship: 'Robert C. Martin',
    category: 'Tecnologia',
    isbn: '9780134494166',
    available: true,
  },
  {
    id: '25',
    title: 'Women in Tech',
    authorship: 'Tarah Wheeler',
    category: 'Carreira',
    isbn: '9781632170668',
    available: false,
  },
];
